"""types for coordinator mode."""
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class WorkerStatus(Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    TIMEOUT = "timeout"


@dataclass
class WorkerTask:
    """task assigned to a worker agent."""
    id: str = field(default_factory=lambda: f"worker-{uuid.uuid4().hex[:8]}")
    name: str = ""
    goal: str = ""  # what the worker should accomplish
    tools: List[str] = field(default_factory=list)  # allowed tools for this worker
    context: str = ""  # additional context from coordinator
    depends_on: List[str] = field(default_factory=list)  # task ids this task is blocked by
    timeout: float = 60.0
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "name": self.name,
            "goal": self.goal,
            "tools": self.tools,
            "context": self.context,
            "depends_on": list(self.depends_on),
            "timeout": self.timeout,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "WorkerTask":
        return cls(
            id=d.get("id", f"worker-{uuid.uuid4().hex[:8]}"),
            name=d.get("name", ""),
            goal=d.get("goal", ""),
            tools=d.get("tools", []),
            context=d.get("context", ""),
            depends_on=list(d.get("depends_on", [])),
            timeout=d.get("timeout", 60.0),
            metadata=d.get("metadata", {}),
        )


@dataclass
class WorkerResult:
    """result from a worker agent."""
    task_id: str
    status: WorkerStatus = WorkerStatus.COMPLETED
    output: str = ""
    findings: List[str] = field(default_factory=list)
    tool_calls: List[Dict[str, Any]] = field(default_factory=list)
    error: Optional[str] = None
    duration: float = 0.0
    input_tokens: int = 0
    output_tokens: int = 0

    @property
    def success(self) -> bool:
        return self.status == WorkerStatus.COMPLETED

    def to_dict(self) -> Dict[str, Any]:
        return {
            "task_id": self.task_id,
            "status": self.status.value,
            "output": self.output,
            "findings": self.findings,
            "tool_calls": self.tool_calls,
            "error": self.error,
            "duration": self.duration,
            "input_tokens": self.input_tokens,
            "output_tokens": self.output_tokens,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "WorkerResult":
        return cls(
            task_id=d["task_id"],
            status=WorkerStatus(d.get("status", "completed")),
            output=d.get("output", ""),
            findings=d.get("findings", []),
            tool_calls=d.get("tool_calls", []),
            error=d.get("error"),
            duration=d.get("duration", 0.0),
            input_tokens=d.get("input_tokens", 0),
            output_tokens=d.get("output_tokens", 0),
        )


@dataclass
class CoordinatorPlan:
    """plan generated by the coordinator for splitting work.

    the coordinator analyzes the main task and decides how to
    split it into worker tasks. this is the sprint contract
    (per anthropic blog) negotiated before execution.
    """
    id: str = field(default_factory=lambda: f"plan-{uuid.uuid4().hex[:8]}")
    main_goal: str = ""
    worker_tasks: List[WorkerTask] = field(default_factory=list)
    synthesis_strategy: str = "merge"  # merge, vote, chain
    created_at: float = field(default_factory=time.time)

    @property
    def worker_count(self) -> int:
        return len(self.worker_tasks)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "main_goal": self.main_goal,
            "worker_tasks": [w.to_dict() for w in self.worker_tasks],
            "synthesis_strategy": self.synthesis_strategy,
            "created_at": self.created_at,
        }

    @classmethod
    def from_dict(cls, d: Dict[str, Any]) -> "CoordinatorPlan":
        return cls(
            id=d.get("id", f"plan-{uuid.uuid4().hex[:8]}"),
            main_goal=d.get("main_goal", ""),
            worker_tasks=[WorkerTask.from_dict(w) for w in d.get("worker_tasks", [])],
            synthesis_strategy=d.get("synthesis_strategy", "merge"),
            created_at=d.get("created_at", time.time()),
        )
