"""
Scaffold module for the Agent SOP Testing Framework.

Provides scaffold generation, validation, and discovery.
"""

from pathlib import Path
from typing import List, Optional, Dict, Any
import re
import yaml

from dokumen_schema import ValidationResult, validate_test_data


def generate_scaffold(
    doc_path: str, output_dir: str = "tests", test_name: Optional[str] = None
) -> str:
    """
    Generate a scaffold YAML file for a documentation file.

    Args:
        doc_path: Path to the documentation file to cover
        output_dir: Directory to write test files
        test_name: Optional custom test name (auto-generated if not provided)

    Returns:
        The scaffold YAML content as a string
    """
    doc = Path(doc_path)

    # Generate test file path
    # docs/api/auth.md -> tests/api/auth.test.yaml
    try:
        # Try to strip first directory component
        parts = doc.parts
        if len(parts) > 1:
            relative = Path(*parts[1:])
        else:
            relative = doc
    except (ValueError, IndexError):
        relative = doc

    test_path = Path(output_dir) / relative.with_suffix(".test.yaml")

    # Generate test name from file (or use provided name)
    if test_name is None:
        test_name = doc.stem.replace("_", "-").replace(" ", "-") + "-test"

    # Build scaffold content
    scaffold = f"""# {test_path.name}
# Generated by: dokumen add {doc_path}

name: {test_name}
reason: |
  # TODO: Describe what this test verifies about {doc.name}

executor:
  system_prompt: "@prompts/executors/question-answering.txt"
  user_prompt: |
    Read {doc_path} and answer the following question:
    # TODO: Specify the question to answer

  tools:
    - list_files
    - read_file

judges:
  - name: qa-judge
    system_prompt: |
      @prompts/judges/question-answering.txt

      # TODO: Add specific evaluation criteria

# timeout: 60
# retries: 0
"""

    return scaffold


def generate_test_scaffold(
    doc_path: str, action: str, assertion: str, test_name: Optional[str] = None
) -> str:
    """
    Generate a test scaffold YAML with user-provided action and assertion.

    Args:
        doc_path: Path to the documentation file to test
        action: What the AI executor should do (becomes user_prompt)
        assertion: Expected result criteria (becomes AI judge assertion)
        test_name: Optional custom test name (auto-generated if not provided)

    Returns:
        The scaffold YAML content as a string
    """
    doc = Path(doc_path)

    # Generate test file path
    try:
        parts = doc.parts
        if len(parts) > 1:
            relative = Path(*parts[1:])
        else:
            relative = doc
    except (ValueError, IndexError):
        relative = doc

    test_path = Path("tests") / relative.with_suffix(".test.yaml")

    # Generate test name from file (or use provided name)
    if test_name is None:
        test_name = doc.stem.replace("_", "-").replace(" ", "-") + "-test"

    # Indent multi-line action and assertion for YAML
    action_lines = action.strip().split("\n")
    action_yaml = "\n    ".join(action_lines)

    assertion_lines = assertion.strip().split("\n")
    assertion_yaml = "\n          ".join(assertion_lines)

    # Build scaffold content
    scaffold = f"""# {test_path.name}
# Generated by: dokumen add {doc_path} --test

name: {test_name}
reason: |
  Test that verifies: {assertion.split(chr(10))[0][:60]}...

executor:
  system_prompt: "@prompts/executors/question-answering.txt"
  user_prompt: |
    {action_yaml}

  tools:
    - list_files
    - read_file

judges:
  - name: assertion-judge
    system_prompt: |
      @prompts/judges/question-answering.txt

      EVALUATION CRITERIA:
      {assertion_yaml}
"""

    return scaffold


def validate_scaffold(data: Dict[str, Any]) -> ValidationResult:
    """
    Validate a scaffold data structure.

    Delegates to dokumen_schema.validate_test_data().

    Args:
        data: Parsed YAML data

    Returns:
        ValidationResult with errors and warnings
    """
    return validate_test_data(data)


def validate_scaffold_file(yaml_path: str) -> ValidationResult:
    """
    Load and validate a scaffold YAML file.

    Args:
        yaml_path: Path to the scaffold file

    Returns:
        ValidationResult with errors and warnings
    """
    try:
        with open(yaml_path) as f:
            data = yaml.safe_load(f)
    except yaml.YAMLError as e:
        return ValidationResult(valid=False, errors=[f"Invalid YAML: {e}"], warnings=[])
    except IOError as e:
        return ValidationResult(valid=False, errors=[f"Cannot read file: {e}"], warnings=[])

    return validate_test_data(data)


def discover_scaffolds(tests_dir: str) -> List[str]:
    """
    Discover all scaffold YAML files in a directory.

    Args:
        tests_dir: Directory to search for .test.yaml files

    Returns:
        List of paths to scaffold files
    """
    tests_path = Path(tests_dir)
    if not tests_path.exists():
        return []

    scaffolds = []
    for path in tests_path.rglob("*.test.yaml"):
        scaffolds.append(str(path))

    return sorted(scaffolds)


def load_scaffold_yaml(yaml_path: str) -> Dict[str, Any]:
    """
    Load a scaffold YAML file.

    Args:
        yaml_path: Path to the scaffold file

    Returns:
        Parsed YAML data

    Raises:
        ValueError: If YAML is invalid
        FileNotFoundError: If file doesn't exist
    """
    with open(yaml_path) as f:
        data = yaml.safe_load(f)

    if data is None:
        raise ValueError(f"Empty YAML file: {yaml_path}")

    return data


def get_scaffold_name(yaml_path: str) -> Optional[str]:
    """
    Get the name from a scaffold file without full parsing.

    Args:
        yaml_path: Path to the scaffold file

    Returns:
        Test name or None if cannot be determined
    """
    try:
        data = load_scaffold_yaml(yaml_path)
        return data.get("name")
    except (IOError, yaml.YAMLError, ValueError):
        return None


def extract_file_references_from_prompts(data: Dict[str, Any]) -> List[str]:
    """
    Extract file path references from executor and judge prompts.

    Looks for patterns like:
    - docs/*.md paths
    - README.md
    - Any path with common file extensions

    Args:
        data: Parsed scaffold YAML data

    Returns:
        List of unique file paths referenced in prompts
    """
    # Common file extensions to look for
    extensions = r"\.(?:md|txt|rst|yaml|yml|json|py|js|ts|html|css|xml|sh|bash|cfg|ini|toml)"

    # Pattern to match file paths
    # Matches: docs/file.md, ./path/to/file.txt, path/file.json, file.md, etc.
    path_pattern = re.compile(
        rf'(?:^|[\s\'"()\[\]{{}}])([./\\]*(?:[\w.-]+[/\\])*[\w.-]+{extensions})',
        re.MULTILINE | re.IGNORECASE,
    )

    found_files = set()

    def extract_from_text(text: str) -> None:
        if not text:
            return
        for match in path_pattern.findall(text):
            # Normalize path separators
            normalized = match.replace("\\", "/")
            # Skip if it looks like a URL or package path
            if "://" in normalized or normalized.startswith("http"):
                continue
            found_files.add(normalized)

    # Extract from executor prompts
    executor = data.get("executor", {})
    if isinstance(executor, dict):
        extract_from_text(executor.get("system_prompt", ""))
        extract_from_text(executor.get("user_prompt", ""))

    # Extract from judge prompts
    judges = data.get("judges", [])
    if isinstance(judges, list):
        for judge in judges:
            if isinstance(judge, dict):
                extract_from_text(judge.get("system_prompt", ""))
                extract_from_text(judge.get("user_prompt", ""))

    return sorted(found_files)


def get_scaffold_files(yaml_path: str) -> List[str]:
    """
    Get the list of file paths referenced by a scaffold.

    Parses executor and judge prompts to find file path references.

    Args:
        yaml_path: Path to the scaffold file

    Returns:
        List of file paths referenced by the scaffold
    """
    try:
        data = load_scaffold_yaml(yaml_path)
        return extract_file_references_from_prompts(data)
    except (IOError, yaml.YAMLError, ValueError):
        return []
